SemiFix Commit GitActios

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -220,3 +220,10 @@ jobs:
       - name: Create release
         uses: ./.github/actions/create-release
         if: startsWith(github.ref, 'refs/tags/')
+      
+        - name: Check if melodii.txt exists
+        run: |
+          if [ ! -f "melodii.txt" ]; then
+            echo "melodii.txt is missing."
+            exit 1
+          fi
